In [7]:
import numpy as np

A = np.matrix('22, 5, 16, 6; 13, 20, 19, 0; 5 9 1 6; 27, 13, 15, 19')
B = np.matrix('10, 5, 20, 20; 5, 21, 22, 27; 26, 19, 22, 3; 27, 8, 18, 7')
c = np.array([24, 3, 17, 7, 11, 2, 21, 2, 24, 18, 3, 11, 14, 25, 2, 20])
d = np.array([3, 15, 24, 22, 19, 24, 4, 29, 6, 3, 20, 1, 11, 25, 26, 6])

print (A)
print (B)
print (c)
print (d)

[[22  5 16  6]
 [13 20 19  0]
 [ 5  9  1  6]
 [27 13 15 19]]
[[10  5 20 20]
 [ 5 21 22 27]
 [26 19 22  3]
 [27  8 18  7]]
[24  3 17  7 11  2 21  2 24 18  3 11 14 25  2 20]
[ 3 15 24 22 19 24  4 29  6  3 20  1 11 25 26  6]


In [8]:
#Element-wise addition A + B
A + B

matrix([[32, 10, 36, 26],
        [18, 41, 41, 27],
        [31, 28, 23,  9],
        [54, 21, 33, 26]])

In [9]:
#ELement-wise subtraction A - B
A - B

matrix([[ 12,   0,  -4, -14],
        [  8,  -1,  -3, -27],
        [-21, -10, -21,   3],
        [  0,   5,  -3,  12]])

In [10]:
#Element-wise multiplication A * B
np.multiply(A, B)

matrix([[220,  25, 320, 120],
        [ 65, 420, 418,   0],
        [130, 171,  22,  18],
        [729, 104, 270, 133]])

In [12]:
#Matrix Multiplication A X B
print (A)
print (B)
A * B

[[22  5 16  6]
 [13 20 19  0]
 [ 5  9  1  6]
 [27 13 15 19]]
[[10  5 20 20]
 [ 5 21 22 27]
 [26 19 22  3]
 [27  8 18  7]]


matrix([[ 823,  567, 1010,  665],
        [ 724,  846, 1118,  857],
        [ 283,  281,  428,  388],
        [1238,  845, 1498, 1069]])

In [14]:
c + d

array([27, 18, 41, 29, 30, 26, 25, 31, 30, 21, 23, 12, 25, 50, 28, 26])

In [15]:
c-d

array([ 21, -12,  -7, -15,  -8, -22,  17, -27,  18,  15, -17,  10,   3,
         0, -24,  14])

In [21]:
#elementwise 
np.multiply(c,d)

array([ 72,  45, 408, 154, 209,  48,  84,  58, 144,  54,  60,  11, 154,
       625,  52, 120])

In [22]:
c*d

array([ 72,  45, 408, 154, 209,  48,  84,  58, 144,  54,  60,  11, 154,
       625,  52, 120])

In [23]:
A+10

matrix([[32, 15, 26, 16],
        [23, 30, 29, 10],
        [15, 19, 11, 16],
        [37, 23, 25, 29]])

In [24]:
B+10

matrix([[20, 15, 30, 30],
        [15, 31, 32, 37],
        [36, 29, 32, 13],
        [37, 18, 28, 17]])

In [25]:
c+15

array([39, 18, 32, 22, 26, 17, 36, 17, 39, 33, 18, 26, 29, 40, 17, 35])

In [26]:
d+15

array([18, 30, 39, 37, 34, 39, 19, 44, 21, 18, 35, 16, 26, 40, 41, 21])

In [27]:
(2*A) + (2*B)

matrix([[ 64,  20,  72,  52],
        [ 36,  82,  82,  54],
        [ 62,  56,  46,  18],
        [108,  42,  66,  52]])

In [28]:
(A+B)*3

matrix([[ 96,  30, 108,  78],
        [ 54, 123, 123,  81],
        [ 93,  84,  69,  27],
        [162,  63,  99,  78]])

In [29]:
(A-B+A-B+B)*4

matrix([[ 136,   20,   48,  -32],
        [  84,   76,   64, -108],
        [ -64,   -4,  -80,   36],
        [ 108,   72,   48,  124]])